// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SyncMe.Data;

#nullable disable

namespace SyncMe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114213246_MigracaoLimpaGS")]
    partial class MigracaoLimpaGS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SyncMe.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORY");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_NAME");

                    b.HasKey("Id");

                    b.ToTable("TB_CATEGORY");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Saúde Mental"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Produtividade"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Soft Skills"
                        });
                });

            modelBuilder.Entity("SyncMe.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONTENT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CATEGORY");

                    b.Property<int>("Difficulty")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_DIFFICULTY");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_MEDIA_URL");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PUBLISH");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_SUMMARY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_TITLE");

                    b.Property<int?>("TrackId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRACK");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TrackId");

                    b.ToTable("TB_CONTENT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Difficulty = 0,
                            MediaUrl = "https://www.youtube.com/watch?v=123",
                            PublishDate = new DateTime(2025, 11, 14, 18, 32, 45, 250, DateTimeKind.Local).AddTicks(7923),
                            Summary = "Aprenda a gerenciar seu tempo com pausas estratégicas.",
                            Title = "Técnica Pomodoro",
                            TrackId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Difficulty = 0,
                            MediaUrl = "https://www.youtube.com/watch?v=456",
                            PublishDate = new DateTime(2025, 11, 14, 18, 32, 45, 250, DateTimeKind.Local).AddTicks(8409),
                            Summary = "Exercícios rápidos de respiração.",
                            Title = "Mindfulness no Trabalho",
                            TrackId = 1
                        });
                });

            modelBuilder.Entity("SyncMe.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TRACK");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRIPTION");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_TITLE");

                    b.HasKey("Id");

                    b.ToTable("TB_TRACK");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Guia prático para reduzir a ansiedade no trabalho.",
                            Title = "Semana Sem Stress"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Como gerir equipes remotas.",
                            Title = "Liderança 4.0"
                        });
                });

            modelBuilder.Entity("SyncMe.Models.Content", b =>
                {
                    b.HasOne("SyncMe.Models.Category", "Category")
                        .WithMany("Contents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SyncMe.Models.Track", "Track")
                        .WithMany("Contents")
                        .HasForeignKey("TrackId");

                    b.Navigation("Category");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SyncMe.Models.Category", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("SyncMe.Models.Track", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
