// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SyncMe.Data;

#nullable disable

namespace SyncMe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SyncMe.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONTENT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_CATEGORY");

                    b.Property<int>("Difficulty")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_DIFFICULTY");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_MEDIA_URL");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_PUBLISH");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_SUMMARY");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_TITLE");

                    b.HasKey("Id");

                    b.ToTable("TB_CONTENT");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Productivity",
                            Difficulty = 0,
                            MediaUrl = "https://youtube.com/...",
                            PublishDate = new DateTime(2025, 11, 13, 13, 47, 36, 330, DateTimeKind.Local).AddTicks(4488),
                            Summary = "Learn to manage your time effectively.",
                            Title = "Pomodoro Technique"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Mental Health",
                            Difficulty = 0,
                            MediaUrl = "https://youtube.com/...",
                            PublishDate = new DateTime(2025, 11, 13, 13, 47, 36, 330, DateTimeKind.Local).AddTicks(4568),
                            Summary = "Reduce stress with breathing exercises.",
                            Title = "Workplace Mindfulness"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
